/**
 * Copyright 2005-2014 Restlet
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: Apache 2.0 or or EPL 1.0 (the "Licenses"). You can
 * select the license that you prefer but you may not use this file except in
 * compliance with one of these Licenses.
 * 
 * You can obtain a copy of the Apache 2.0 license at
 * http://www.opensource.org/licenses/apache-2.0
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://restlet.com/products/restlet-framework
 * 
 * Restlet is a registered trademark of Restlet S.A.S.
 */

package org.restlet.test.ext.odata.deepexpand.model;

import java.util.List;

import org.restlet.test.ext.odata.deepexpand.model.Category;
import org.restlet.test.ext.odata.deepexpand.model.Company;
import org.restlet.test.ext.odata.deepexpand.model.Multilingual;
import org.restlet.test.ext.odata.deepexpand.model.Registration;

/**
 * Generated by the generator tool for the OData extension for the Restlet
 * framework.<br>
 * 
 * @see <a
 *      href="http://praktiki.metal.ntua.gr/CoopOData/CoopOData.svc/$metadata">Metadata
 *      of the target OData service</a>
 * 
 */
public class Category {

    private int id;

    private String path;

    private Tracking tracking;

    private List<Category> childCategories;

    private List<Company> companies;

    private Multilingual name;

    private Category parentCategory;

    private List<Registration> preferredByRegistrations;

    /**
     * Constructor without parameter.
     * 
     */
    public Category() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public Category(int id) {
        this();
        this.id = id;
    }

    /**
     * Returns the value of the "id" attribute.
     * 
     * @return The value of the "id" attribute.
     */
    public int getId() {
        return id;
    }

    /**
     * Returns the value of the "path" attribute.
     * 
     * @return The value of the "path" attribute.
     */
    public String getPath() {
        return path;
    }

    /**
     * Returns the value of the "tracking" attribute.
     * 
     * @return The value of the "tracking" attribute.
     */
    public Tracking getTracking() {
        return tracking;
    }

    /**
     * Returns the value of the "childCategories" attribute.
     * 
     * @return The value of the "childCategories" attribute.
     */
    public List<Category> getChildCategories() {
        return childCategories;
    }

    /**
     * Returns the value of the "companies" attribute.
     * 
     * @return The value of the "companies" attribute.
     */
    public List<Company> getCompanies() {
        return companies;
    }

    /**
     * Returns the value of the "name" attribute.
     * 
     * @return The value of the "name" attribute.
     */
    public Multilingual getName() {
        return name;
    }

    /**
     * Returns the value of the "parentCategory" attribute.
     * 
     * @return The value of the "parentCategory" attribute.
     */
    public Category getParentCategory() {
        return parentCategory;
    }

    /**
     * Returns the value of the "preferredByRegistrations" attribute.
     * 
     * @return The value of the "preferredByRegistrations" attribute.
     */
    public List<Registration> getPreferredByRegistrations() {
        return preferredByRegistrations;
    }

    /**
     * Sets the value of the "id" attribute.
     * 
     * @param id
     *            The value of the "id" attribute.
     */
    public void setId(int id) {
        this.id = id;
    }

    /**
     * Sets the value of the "path" attribute.
     * 
     * @param path
     *            The value of the "path" attribute.
     */
    public void setPath(String path) {
        this.path = path;
    }

    /**
     * Sets the value of the "tracking" attribute.
     * 
     * @param tracking
     *            The value of the "tracking" attribute.
     */
    public void setTracking(Tracking tracking) {
        this.tracking = tracking;
    }

    /**
     * Sets the value of the "childCategories" attribute.
     * 
     * @param childCategories
     *            " The value of the "childCategories" attribute.
     */
    public void setChildCategories(List<Category> childCategories) {
        this.childCategories = childCategories;
    }

    /**
     * Sets the value of the "companies" attribute.
     * 
     * @param companies
     *            " The value of the "companies" attribute.
     */
    public void setCompanies(List<Company> companies) {
        this.companies = companies;
    }

    /**
     * Sets the value of the "name" attribute.
     * 
     * @param name
     *            " The value of the "name" attribute.
     */
    public void setName(Multilingual name) {
        this.name = name;
    }

    /**
     * Sets the value of the "parentCategory" attribute.
     * 
     * @param parentCategory
     *            " The value of the "parentCategory" attribute.
     */
    public void setParentCategory(Category parentCategory) {
        this.parentCategory = parentCategory;
    }

    /**
     * Sets the value of the "preferredByRegistrations" attribute.
     * 
     * @param preferredByRegistrations
     *            " The value of the "preferredByRegistrations" attribute.
     */
    public void setPreferredByRegistrations(
            List<Registration> preferredByRegistrations) {
        this.preferredByRegistrations = preferredByRegistrations;
    }

}