/**
 * Copyright 2005-2014 Restlet
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: Apache 2.0 or or EPL 1.0 (the "Licenses"). You can
 * select the license that you prefer but you may not use this file except in
 * compliance with one of these Licenses.
 * 
 * You can obtain a copy of the Apache 2.0 license at
 * http://www.opensource.org/licenses/apache-2.0
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://restlet.com/products/restlet-framework
 * 
 * Restlet is a registered trademark of Restlet S.A.S.
 */

package org.restlet.test.ext.odata.cafecustofeeds;

/**
 * Generated by the generator tool for the WCF Data Services extension for the
 * Restlet framework.<br>
 * 
 * @see <a href="http://localhost:8111/CafeCustoFeeds.svc/$metadata">Metadata of
 *      the target WCF Data Services</a>
 * 
 */
public class Item {

    private String description;

    private String id;

    /**
     * Constructor without parameter.
     * 
     */
    public Item() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public Item(String id) {
        this();
        this.id = id;
    }

    /**
     * Returns the value of the description attribute.
     * 
     * @return The value of the description attribute.
     */
    public String getDescription() {
        return description;
    }

    /**
     * Returns the value of the id attribute.
     * 
     * @return The value of the id attribute.
     */
    public String getId() {
        return id;
    }

    /**
     * Sets the value of the description attribute.
     * 
     * @param Description
     *            The value of the description attribute.
     */
    public void setDescription(String description) {
        this.description = description;
    }

    /**
     * Sets the value of the id attribute.
     * 
     * @param ID
     *            The value of the id attribute.
     */
    public void setId(String id) {
        this.id = id;
    }

}
