package org.restlet.test.ext.odata.complexcrud;


import java.util.ArrayList;
import java.util.List;

import org.restlet.test.ext.odata.cafe.Item;

/**
* Generated by the generator tool for the WCF Data Services extension for the Restlet framework.<br>
*
* @see <a href="http://localhost:8111/Cafe.svc/$metadata">Metadata of the target WCF Data Services</a>
*
*/
public class Cafe {

private Point spatial;
private String city;

private String id;
private String name;
private int zipCode;

private List<Item> items = new ArrayList<Item>();    /**
     * Constructor without parameter.
     * 
     */
    public Cafe() {
        super();
    }

    /**
     * Constructor.
     * 
     * @param id
     *            The identifiant value of the entity.
     */
    public Cafe(String id) {
        this();
        this.id = id;
    }
    
   /**
    * Returns the value of the city attribute.
    *
    * @return The value of the city attribute.
    */
   public String getCity() {
      return city;
   }
   
   
   /**
    * Returns the value of the id attribute.
    *
    * @return The value of the id attribute.
    */
   public String getId() {
      return id;
   }
   
   /**
    * Returns the value of the name attribute.
    *
    * @return The value of the name attribute.
    */
   public String getName() {
      return name;
   }
   
   /**
    * Returns the value of the zipCode attribute.
    *
    * @return The value of the zipCode attribute.
    */
   public int getZipCode() {
      return zipCode;
   }
   
   
   /**
    * Returns the value of the items attribute.
    *
    * @return The value of the items attribute.
    */
   public List<Item> getItems() {
      return items;
   }
   

   /**
    * Sets the value of the city attribute.
    *
    * @param City
    *     The value of the city attribute.
    */
   public void setCity(String city) {
      this.city = city;
   }
   
   
   /**
    * Sets the value of the id attribute.
    *
    * @param ID
    *     The value of the id attribute.
    */
   public void setId(String id) {
      this.id = id;
   }
   
   /**
    * Sets the value of the name attribute.
    *
    * @param Name
    *     The value of the name attribute.
    */
   public void setName(String name) {
      this.name = name;
   }
   
   /**
    * Sets the value of the zipCode attribute.
    *
    * @param ZipCode
    *     The value of the zipCode attribute.
    */
   public void setZipCode(int zipCode) {
      this.zipCode = zipCode;
   }
   

   /**
    * Sets the value of the items attribute.
    *
    * @param items
    *     The value of the items attribute.
    */
   public void setItems(List<Item> items) {
      this.items = items;
   }

/**
 * @return the spatial
 */
public Point getSpatial() {
	return spatial;
}

/**
 * @param spatial the spatial to set
 */
public void setSpatial(Point spatial) {
	this.spatial = spatial;
}


}
