/**
 * Copyright 2005-2014 Restlet
 * 
 * The contents of this file are subject to the terms of one of the following
 * open source licenses: Apache 2.0 or or EPL 1.0 (the "Licenses"). You can
 * select the license that you prefer but you may not use this file except in
 * compliance with one of these Licenses.
 * 
 * You can obtain a copy of the Apache 2.0 license at
 * http://www.opensource.org/licenses/apache-2.0
 * 
 * You can obtain a copy of the EPL 1.0 license at
 * http://www.opensource.org/licenses/eclipse-1.0
 * 
 * See the Licenses for the specific language governing permissions and
 * limitations under the Licenses.
 * 
 * Alternatively, you can obtain a royalty free commercial license with less
 * limitations, transferable or non-transferable, directly at
 * http://restlet.com/products/restlet-framework
 * 
 * Restlet is a registered trademark of Restlet S.A.S.
 */

package org.restlet.ext.apispark.internal.conversion;

import org.restlet.data.Status;
import org.restlet.engine.util.StringUtils;
import org.restlet.ext.apispark.internal.model.Section;

public class ConversionUtils {

    /**
     * Generates a name for a resource computed from its path. The name is
     * composed of all alphanumeric characters in camel case.<br/>
     * Ex: /contacts/{contactId} => ContactsContactId
     * 
     * @param uri
     *            The URI of the Resource
     * @return The Resource's name computed from the path.
     */
    public static String processResourceName(String uri) {
        StringBuilder sb = new StringBuilder();
        String[] split = uri.replaceAll("\\{", "").replaceAll("\\}", "")
                .split("/");
        for (String str : split) {
            sb.append(StringUtils.firstUpper(str));
        }
        return sb.toString();
    }

    /**
     * Generates a name for the response given the status code.
     * The generated name will be "Success" in case of success, "Error [statusCode]" in case of error and "Status
     * [statusCode] otherwise.
     * 
     * @param statusCode
     *            The status code of the response.
     * @return The generated name.
     */
    public static String generateResponseName(int statusCode) {
        String autoGeneratedName = "Status " + statusCode;
        if (Status.isSuccess(statusCode)) {
            autoGeneratedName = "Success";
        } else if (Status.isError(statusCode)) {
            autoGeneratedName = "Error " + statusCode;
        }
        return autoGeneratedName;
    }

    /**
     * Creates a valid {@link Section} name from the given package name.
     * 
     * @param packageName
     *            The package name to process.
     * @return a valid {@link Section} name.
     */
    public static String formatSectionNameFromPackageName(String packageName) {
        return packageName.replaceAll("\\.", "_");
    }

}
